## TYPES OF ATTRIBUTES:

1. Qualitative (Categorical)

   -> Ordinal => Eg. Coffee cup size    small < medium < large

   -> Nominal => Eg. Mug Color (blue, black etc.)   blue < black


2. Quantitative (Numeric)

In [30]:
import pandas as pd

In [28]:
df = pd.read_csv("Travel.csv")

In [31]:
## Display first 5 records

df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [32]:
## Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

In [ ]:
df.describe()

# 50% -> median

,CustomerID,ProdTaken,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,MonthlyIncome
count,4888.000000,4888.000000,4662.000000,4888.000000,4637.000000,4888.000000,4843.000000,4862.000000,4748.000000,4888.000000,4888.000000,4888.000000,4822.000000,4655.000000
mean,202443.500000,0.188216,37.622265,1.654255,15.490835,2.905074,3.708445,3.581037,3.236521,0.290917,3.078151,0.620295,1.187267,23619.853491
std,1411.188388,0.390925,9.316387,0.916583,8.519643,0.724891,1.002509,0.798009,1.849019,0.454232,1.365792,0.485363,0.857861,5380.698361
min,200000.000000,0.000000,18.000000,1.000000,5.000000,1.000000,1.000000,3.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1000.000000
25%,201221.750000,0.000000,31.000000,1.000000,9.000000,2.000000,3.000000,3.000000,2.000000,0.000000,2.000000,0.000000,1.000000,20346.000000
50%,202443.500000,0.000000,36.000000,1.000000,13.000000,3.000000,4.000000,3.000000,3.000000,0.000000,3.000000,1.000000,1.000000,22347.000000
75%,203665.250000,0.000000,44.000000,3.000000,20.000000,3.000000,4.000000,4.000000,4.000000,1.000000,4.000000,1.000000,2.000000,25571.000000
max,204887.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,5.000000,1.000000,3.000000,98678.000000

## Data cleaning

1. Handling missing values

In [34]:
## Check missing values

df.isna().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

Common ways of filling missing values

-> Fill with mean / median (for numeric columns) (Median preferred when skewed data/outliers)

-> Fill with mode (for categorical data)

-> Fill with 0

-> Remove entire row/column

In [11]:
## Fill age with mean

df["Age"] = df["Age"].fillna(df["Age"].mean())

In [12]:
df["Age"].isna().sum()

np.int64(0)

In [14]:
df["TypeofContact"] = df["TypeofContact"].fillna(df["TypeofContact"].mode()[0])
df["TypeofContact"].isna().sum()

np.int64(0)

Homework => Perform data cleaning of rest of the columns

#### 2. Drop Duplicates

In [19]:
df.duplicated().sum()

np.int64(0)

In [21]:
df = df.drop_duplicates()

## ENCODING => Converting categorical column to numerical column
### Types:
    1. Label Encoding (Ordinal)
    2. One hot Encoding (Nominal)

## LABEL ENCODING

Cup size: 

small-> 0

medium -> 1

large -> 2


2 > 1 > 0

large > medium > small

In [22]:
df = pd.DataFrame({
    "Customer": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Cup Size": ["Small", "Medium", "Large", "Small", "Large"]
})

df

  Customer Cup Size
0    Alice    Small
1      Bob   Medium
2  Charlie    Large
3    David    Small
4      Eva    Large

In [24]:
size_mapping = {
    "Small": 0,
    "Medium": 1,
    "Large": 2
}

df["Cup Size"] = df["Cup Size"].map(size_mapping)

df

  Customer  Cup Size
0    Alice         0
1      Bob         1
2  Charlie         2
3    David         0
4      Eva         2

## One hot encoding

0-> black
1-> green
2-> blue

2>1>0

blue > green > black


colour

blue

black

black

green


blue   black    green

1       0           0

0       1           0

0       1           0

0       0           1

In [25]:
df = pd.DataFrame({
    "Color": ["Blue", "Black", "Black", "Green"]
})

df

   Color
0   Blue
1  Black
2  Black
3  Green

In [26]:
df_encoded = pd.get_dummies(df, columns=["Color"])

df_encoded

   Color_Black  Color_Blue  Color_Green
0        False        True        False
1         True       False        False
2         True       False        False
3        False       False         True