## PANDAS

-> Pandas is an open-source Python library used for data manipulation, analysis and cleaning. 

-> Used when dealing with tabular data as it provides fast and flexible tools to work with tabular data.

### 1. Pandas installation

In [17]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\dhvani\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dhvani\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dhvani\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dhvani\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dhvani\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dhvani\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

### 2. Data Structures in Pandas

-> Series

-> DataFrame

### Series : 1-d array like object, can hold any datatype, similar to column in a table

In [3]:
## creating series from a list

data=[1,2,3,4,5]
series = pd.Series(data)
print("series \n" ,series)
print(type(series))

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
## create series from a dictionary

data={'a':1, 'b':2, 'c':3}

series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

### DataFrame : 2-dimensional data structure with labeled axes (rows and columns).

#### Ways of creating DataFrame

1. Create a dataframe from a dictionary of a list
2. create a dataframe from a list of dictionaries
3. Loading data from csv

In [6]:
## create a dataframe from dictionary of list

data = {
    'name':['Krish', 'John', 'Jack'],
    'age' : [25,30,45],
    'city' : ['Bangalore', 'New York', 'Florida']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

    name  age       city
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida
<class 'pandas.core.frame.DataFrame'>

In [7]:
## create a dataframe from a list of dictionaries

data = [
    {'name':'Krish', 'Age':32, 'City': 'Bangalore'},
    {'name': 'John', 'Age':34, 'City':'Bangalore'},
    {'name':'Bappy', 'Age':32, 'City':"Bangalore"},
    {'name':'Jack', 'Age':32, 'City': 'Bangalore'}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

    name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   Jack   32  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [8]:
## Loading from csv

df_sales = pd.read_csv("sales_data.csv")
df_sales

,Date,Product,Region,Salesperson,Units_Sold,Unit_Price,Revenue,Discount(%),Profit
0,2023-12-03,Laptop,North,Kabir,9,29960,269640,10,41254.92
1,2023-03-12,Tablet,East,Kabir,14,20063,280882,0,61794.04
2,2023-11-28,Laptop,South,Aarav,18,78725,1417050,10,191301.75
3,2023-03-27,Tablet,North,Kabir,13,56916,739908,10,193115.99
4,2023-06-27,Phone,West,Aarav,15,58217,873255,5,190806.22
...,...,...,...,...,...,...,...,...,...
195,2023-10-14,Phone,West,Diya,15,4901,73515,0,21319.35
196,2023-06-01,Laptop,South,Meera,13,69011,897143,0,134571.45
197,2023-10-21,Tablet,North,Rohan,4,57991,231964,10,54279.58
198,2023-10-05,Smartwatch,North,Isha,12,26890,322680,15,63083.94
199,2023-12-21,Smartwatch,South,Aarav,8,22478,179824,10,22657.82

In [10]:
df_sales.head()

,Date,Product,Region,Salesperson,Units_Sold,Unit_Price,Revenue,Discount(%),Profit
0,2023-12-03,Laptop,North,Kabir,9,29960,269640,10,41254.92
1,2023-03-12,Tablet,East,Kabir,14,20063,280882,0,61794.04
2,2023-11-28,Laptop,South,Aarav,18,78725,1417050,10,191301.75
3,2023-03-27,Tablet,North,Kabir,13,56916,739908,10,193115.99
4,2023-06-27,Phone,West,Aarav,15,58217,873255,5,190806.22

In [26]:
df_sales.tail()

,Date,Product,Region,Salesperson,Units_Sold,Unit_Price,Revenue,Discount(%),Profit
195,2023-10-14,Phone,West,Diya,15,4901,73515,0,21319.35
196,2023-06-01,Laptop,South,Meera,13,69011,897143,0,134571.45
197,2023-10-21,Tablet,North,Rohan,4,57991,231964,10,54279.58
198,2023-10-05,Smartwatch,North,Isha,12,26890,322680,15,63083.94
199,2023-12-21,Smartwatch,South,Aarav,8,22478,179824,10,22657.82

### Selecting particular columns in DataFrame

In [27]:
## Single column

df_sales["Product"]

0          Laptop
1          Tablet
2          Laptop
3          Tablet
4           Phone
          ...
195         Phone
196        Laptop
197        Tablet
198    Smartwatch
199    Smartwatch
Name: Product, Length: 200, dtype: object

In [11]:
## Multiple columns:
df_sales[["Product", "Units_Sold"]]

        Product  Units_Sold
0        Laptop           9
1        Tablet          14
2        Laptop          18
3        Tablet          13
4         Phone          15
..          ...         ...
195       Phone          15
196      Laptop          13
197      Tablet           4
198  Smartwatch          12
199  Smartwatch           8

[200 rows x 2 columns]

### Add and drop columns in DataFrame

In [13]:
df_sales = df_sales.drop("Revenue", axis=1)

In [14]:
df_sales.head()

,Date,Product,Region,Salesperson,Units_Sold,Unit_Price,Discount(%),Profit
0,2023-12-03,Laptop,North,Kabir,9,29960,10,41254.92
1,2023-03-12,Tablet,East,Kabir,14,20063,0,61794.04
2,2023-11-28,Laptop,South,Aarav,18,78725,10,191301.75
3,2023-03-27,Tablet,North,Kabir,13,56916,10,193115.99
4,2023-06-27,Phone,West,Aarav,15,58217,5,190806.22

In [31]:
df_sales["Revenue"] = df_sales["Units_Sold"] * df_sales["Unit_Price"]

In [32]:
df_sales.head()

,Date,Product,Region,Salesperson,Units_Sold,Unit_Price,Discount(%),Profit,Revenue
0,2023-12-03,Laptop,North,Kabir,9,29960,10,41254.92,269640
1,2023-03-12,Tablet,East,Kabir,14,20063,0,61794.04,280882
2,2023-11-28,Laptop,South,Aarav,18,78725,10,191301.75,1417050
3,2023-03-27,Tablet,North,Kabir,13,56916,10,193115.99,739908
4,2023-06-27,Phone,West,Aarav,15,58217,5,190806.22,873255

### Selecting and filtering data

In [17]:
df_sales[df_sales["Units_Sold"]>=18]

,Date,Product,Region,Salesperson,Units_Sold,Unit_Price,Discount(%),Profit
2,2023-11-28,Laptop,South,Aarav,18,78725,10,191301.75
6,2023-04-12,Tablet,East,Meera,19,12095,5,58944.98
14,2023-08-14,Smartwatch,West,Kabir,19,23059,0,61336.94
17,2023-09-02,Phone,South,Meera,20,56106,5,287823.78
18,2023-05-22,Headphones,West,Aarav,20,37159,10,147149.64
51,2023-11-17,Headphones,East,Kabir,20,37558,10,114927.48
52,2023-06-13,Headphones,East,Isha,20,40147,0,152558.60
53,2023-08-12,Laptop,West,Isha,20,30993,0,136369.20
62,2023-10-02,Smartwatch,West,Meera,20,7974,0,39870.00
65,2023-10-26,Laptop,North,Kabir,19,51963,10,151056.44
68,2023-02-17,Laptop,West,Isha,18,16951,5,84060.01
94,2023-05-12,Phone,East,Aarav,18,42611,0,191749.50
95,2023-11-13,Laptop,West,Isha,20,12264,15,45867.36
97,2023-04-04,Tablet,South,Meera,19,29044,0,88293.76
103,2023-04-05,Tablet,North,Kabir,19,31066,15,85291.70
109,2023-08-30,Smartwatch,East,Isha,19,22718,15,36689.57
110,2023-06-17,Headphones,East,Rohan,20,24389,0,131700.60
122,2023-10-11,Laptop,West,Diya,19,63961,5,184719.37
140,2023-11-10,Tablet,East,Diya,19,15464,0,58763.20
141,2023-11-29,Smartwatch,East,Kabir,19,48270,0,220111.20
146,2023-07-27,Headphones,North,Kabir,19,16019,10,65741.98
156,2023-01-18,Headphones,East,Kabir,20,47598,10,179920.44
162,2023-11-16,Tablet,North,Meera,19,11610,15,33750.27
169,2023-12-25,Laptop,East,Rohan,19,10580,0,34173.40
174,2023-09-13,Tablet,South,Diya,19,25249,0,110338.13
181,2023-08-07,Laptop,East,Diya,19,33372,0,145835.64
187,2023-04-23,Smartwatch,North,Isha,19,12562,0,62056.28

In [16]:
df_sales["Units_Sold"]>=18

0      False
1      False
2       True
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: Units_Sold, Length: 200, dtype: bool

#### Q-> Sales data where Region = South

In [18]:
df_sales[df_sales["Region"]=="South"]

,Date,Product,Region,Salesperson,Units_Sold,Unit_Price,Discount(%),Profit
2,2023-11-28,Laptop,South,Aarav,18,78725,10,191301.75
5,2023-05-22,Smartwatch,South,Kabir,5,49452,5,65771.16
7,2023-11-09,Phone,South,Diya,11,13865,15,25927.55
10,2023-01-01,Phone,South,Isha,10,41100,10,103572.00
15,2023-02-22,Tablet,South,Kabir,12,33249,10,57454.27
17,2023-09-02,Phone,South,Meera,20,56106,5,287823.78
20,2023-11-28,Smartwatch,South,Rohan,10,48438,0,135626.40
21,2023-02-01,Phone,South,Meera,9,2921,15,4022.22
24,2023-07-06,Headphones,South,Rohan,14,4862,10,11639.63
29,2023-03-01,Headphones,South,Rohan,15,40269,5,160673.31
30,2023-08-17,Tablet,South,Kabir,9,54379,15,74879.88
37,2023-08-07,Laptop,South,Isha,16,59281,5,126149.97
41,2023-06-20,Headphones,South,Meera,11,43155,0,56964.60
44,2023-06-06,Laptop,South,Isha,11,35207,15,42794.11
46,2023-11-17,Laptop,South,Kabir,15,69809,15,231416.84
48,2023-07-24,Headphones,South,Aarav,15,38924,5,149760.09
50,2023-02-20,Phone,South,Isha,13,47845,15,105737.45
55,2023-02-22,Phone,South,Aarav,8,38760,15,63256.32
58,2023-04-27,Phone,South,Aarav,13,59913,15,119166.96
63,2023-01-12,Laptop,South,Diya,7,45662,15,62488.45
71,2023-11-20,Headphones,South,Kabir,3,52923,10,22862.74
76,2023-06-13,Headphones,South,Meera,5,4315,10,4660.20
85,2023-11-30,Laptop,South,Rohan,9,49660,0,53632.80
91,2023-08-26,Headphones,South,Diya,12,18902,5,56025.53
92,2023-01-13,Laptop,South,Rohan,12,67416,10,218427.84
97,2023-04-04,Tablet,South,Meera,19,29044,0,88293.76
98,2023-05-24,Smartwatch,South,Isha,9,27261,0,58883.76
99,2023-10-07,Headphones,South,Isha,11,42706,0,89255.54
111,2023-07-24,Laptop,South,Meera,13,41927,0,125361.73
115,2023-04-04,Tablet,South,Diya,10,20030,10,27040.50
116,2023-06-14,Tablet,South,Rohan,2,37052,15,8188.49
119,2023-06-03,Headphones,South,Kabir,16,37381,10,113040.14
121,2023-10-13,Headphones,South,Meera,17,36734,10,101165.44
129,2023-06-04,Tablet,South,Meera,16,2547,0,9372.96
130,2023-07-05,Tablet,South,Isha,7,56729,5,75449.57
139,2023-01-23,Smartwatch,South,Isha,11,13208,10,32689.80
147,2023-03-01,Laptop,South,Isha,16,32282,10,130161.02
149,2023-02-05,Laptop,South,Diya,16,72446,10,239941.15
155,2023-01-17,Smartwatch,South,Diya,12,28434,15,40603.75
157,2023-09-16,Tablet,South,Diya,7,14254,5,20853.60
164,2023-03-08,Headphones,South,Meera,12,5035,15,15407.10
165,2023-01-14,Smartwatch,South,Isha,9,19982,15,41272.82
173,2023-07-01,Headphones,South,Diya,6,27651,0,39817.44
174,2023-09-13,Tablet,South,Diya,19,25249,0,110338.13
183,2023-02-24,Smartwatch,South,Diya,6,52941,5,69405.65
188,2023-11-30,Tablet,South,Aarav,14,10689,10,39057.61
190,2023-08-28,Laptop,South,Meera,8,43574,10,53334.58
196,2023-06-01,Laptop,South,Meera,13,69011,0,134571.45
199,2023-12-21,Smartwatch,South,Aarav,8,22478,10,22657.82

In [ ]:
df_sales.groupby(["Region", "Product"])["Units_Sold"].sum()

Region  Product
East    Headphones    127
        Laptop         63
        Phone          85
        Smartwatch    111
        Tablet        154
North   Headphones    113
        Laptop        104
        Phone          69
        Smartwatch    103
        Tablet        130
South   Headphones    137
        Laptop        154
        Phone          84
        Smartwatch     70
        Tablet        115
West    Headphones     77
        Laptop        172
        Phone         115
        Smartwatch    129
        Tablet         27
Name: Units_Sold, dtype: int64

In [29]:
df_sales.groupby("Region")["Product"].mode()[0]

AttributeError: 'SeriesGroupBy' object has no attribute 'mode'